### ISSUE TITLE
FreeBSD does not react to FORWARD-TSN-Chunk without any previous DATA-Chunks

### ISSUE THREAD

**Issue by TheAomx** [sctplab/pr-sctp-improved#1]
FreeBSD does not seem to react to any FORWARD-TSN-Chunks received before any DATA chunks. Only after one DATA-Chunk was processed, there seems to be a reaction to incoming FORWARD-TSN-Chunks. See the following failing (more specific: they are hanging, because the kernel does not send a SACK-Chunk) packetdrill tests for details:
- https://github.com/nplab/PR_SCTP_Testsuite/blob/master/packetdrill-tests/receiver-side-implementation/receiver-side-implementation-1.pkt
- https://github.com/nplab/PR_SCTP_Testsuite/blob/master/packetdrill-tests/receiver-side-implementation/receiver-side-implementation-3.pkt
- https://github.com/nplab/PR_SCTP_Testsuite/blob/master/packetdrill-tests/receiver-side-implementation/receiver-side-implementation-5.pkt
- https://github.com/nplab/PR_SCTP_Testsuite/blob/master/packetdrill-tests/receiver-side-implementation/receiver-side-implementation-6.pkt

**Comment by tuexen** [comment]
Fixed in https://svnweb.freebsd.org/changeset/base/304837.
