### ISSUE TITLE
ABORT-Chunk is sent instead of SHUTDOWN-Chunk

### ISSUE THREAD

**Issue by TheAomx** [sctplab/pr-sctp-improved#8]
In the following test-case after calling close the FreeBSD-Kernel sends an ABORT-Chunk instead of an expected SHUTDOWN-Chunk:
- https://github.com/nplab/PR_SCTP_Testsuite/blob/master/i-forward-tsn/receiver-side-implementation/receiver-side-implementation-11.pkt

**Comment by tuexen** [comment]
You are injecting two messages but the application call `sctp_recvmsg()` only once. So I would expect the kernel to send an `ABORT`- chunk. Please change the code to read all messages from the kernel before calling `close()`.

**Comment by TheAomx** [comment]
If this is expected then why does the following test-case (which is almost identical expect that it uses DATA and FORWARD-TSN-Chunks) succeed:
- https://github.com/nplab/PR_SCTP_Testsuite/blob/master/receiver-side-implementation/receiver-side-implementation-11.pkt

Sorry, i was wrong. It fails also. I will adjust both test cases.

**Comment by TheAomx** [comment]
I adjusted both test cases and they both pass now. This can be closed now...!
